import { type SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  docSidebar: [
    "introduction/index",

    {
      type: "category",
      label: "${GETTING_STARTED}",
      items: [
        {
          type: "category",
          label: "${INSTALLATION}",
          link: { type: "doc", id: "getting-started/installation/index" },
          items: [
            "getting-started/installation/binary",
            "getting-started/installation/docker",
            "getting-started/installation/source",
            "getting-started/installation/use-1panel",
            "getting-started/installation/use-aapanel",
            "getting-started/installation/use-xppanel",
          ],
        },
        "getting-started/webui",
        "getting-started/configuration",
        "getting-started/upgrade",
        "getting-started/backup",
      ],
      collapsed: false,
    },

    {
      type: "category",
      label: "${TUTORIAL}",
      link: { type: "doc", id: "tutorial/index" },
      items: [
        "tutorial/overview",
        "tutorial/workflows",
        "tutorial/credentials",
        "tutorial/awesome-community-cases",
      ],
      collapsed: false,
    },

    {
      type: "category",
      label: "${REFERENCE}",
      items: ["reference/mechanism", "reference/providers", "reference/faq"],
      collapsed: false,
    },

    {
      type: "category",
      label: "${ABOUT}",
      items: ["about/releases", "about/contributing", "about/disclaimer"],
      collapsed: false,
    },

    {
      type: "category",
      label: "${MIGRATIONS}",
      link: { type: "doc", id: "migrations/index" },
      items: ["migrations/migrate-to-v0.4", "migrations/migrate-to-v0.3"],
      collapsed: false,
    },
  ],
};

export default sidebars;
